#!/usr/bin/env bash
# Applies the Uxdata branding to a clean checkout of useplunk/plunk.
#
#   patch/apply.sh <upstream-dir>
#
# Env: DASHBOARD_URL (default https://plunk.uxdata.co) — used for the logo in the
# system emails and for og:image, which need absolute URLs.
#
# Idempotent (re-running on an already branded tree is a no-op) and loud: it exits
# non-zero if an expected anchor is missing or a new user-visible "Plunk" string
# appears upstream, so a version bump can never ship half-branded.
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
up="${1:?usage: patch/apply.sh <upstream-dir>}"
up="$(cd "$up" && pwd)"
DASHBOARD_URL="${DASHBOARD_URL:-https://plunk.uxdata.co}"

[ -f "$up/apps/web/package.json" ] && [ -f "$up/Dockerfile" ] || { echo "not a plunk checkout: $up" >&2; exit 64; }

want="$(tr -d '[:space:]' < "$here/UPSTREAM_VERSION")"
if git -C "$up" rev-parse --git-dir >/dev/null 2>&1; then
  have="$(git -C "$up" describe --tags --exact-match 2>/dev/null || true)"
  [ "$have" = "$want" ] || { echo "upstream checkout is at '${have:-<no tag>}', UPSTREAM_VERSION says '$want'" >&2; exit 65; }
fi

# 1. Assets: logo, favicons, PWA icons, og image (generated by brand/generate.mjs).
expected=(assets/logo.png assets/logo.svg favicon.ico favicon/favicon.ico favicon/favicon.svg
  favicon/favicon-16x16.png favicon/favicon-32x32.png favicon/apple-touch-icon.png
  favicon/android-chrome-192x192.png favicon/android-chrome-512x512.png
  favicon/mstile-150x150.png favicon/safari-pinned-tab.svg)
for f in "${expected[@]}"; do
  [ -f "$up/apps/web/public/$f" ] || { echo "upstream no longer ships apps/web/public/$f — review the asset list" >&2; exit 1; }
  [ -f "$here/brand/web/$f" ] || { echo "missing brand/web/$f (run brand/generate.mjs)" >&2; exit 1; }
done
cp -R "$here/brand/web/." "$up/apps/web/public/"
echo "assets copied: $(find "$here/brand/web" -type f | wc -l | tr -d ' ') files"

# 2. Strings (anchored replacements + leftover guard).
node "$here/patch/brand.mjs" "$up" "$DASHBOARD_URL"
